services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8089:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home:
version: '3.0'

#Create a docker-compose.yml file under the path /root/jenkins. Once done, run a docker-compose up. Name: jenkins Image: jenkins/jenkins:lts ports: hostport: 8089 --> Container Port: 8080 hostport: 50000 --> Container Port: 50000


#Volume jenkins_home mapped to directory /var/jenkins_home

# ports: host-port:container-port